### ISSUE TITLE
neato package installing issue

### ISSUE THREAD

**Issue by koliajaykr** [tierneyn/neato#1]
Is neato package still available to download from the CRAN? I faced issues in downloading this package.

**Comment by njtierney** [comment]
Hey there!

alas, neato is not on CRAN, only on github - install with 

```r
# devtools must be installed)
# install.packages("devtools")
devtools::install_github("njtierney/neato")
```
 at the moment it is more of a collection of functions I use somewhat regularly. Some of these functions have made their way into packages like `visdat` - which is now on CRAN (https://cran.r-project.org/web/packages/visdat/index.html).

Is there a particular function you are wanting to use?

**Comment by koliajaykr** [comment]
Thank you, it is working fine now. I used the  ggplot_missing() function.

**Comment by njtierney** [comment]
Ok great!

You should check out the `vis_dat` and `vis_miss` functions from the visdat package:

``` r
library(visdat)

vis_dat(airquality)
```

![](http://i.imgur.com/qPSOFM9.png)

``` r
vis_miss(airquality)
```

![](http://i.imgur.com/EdnDzep.png)

You can get more info about it here: http://visdat.njtierney.com/

**Comment by koliajaykr** [comment]
Thank you, these new functions are better than the earlier one. Thanks once again. It is only me or it is really difficult to reach timely to the right R packages.
